### OK
POST http://0.0.0.0:3000/signup
Content-Type: application/json

{
    "username": "alex",
    "password": "alex1990"
}

###
POST http://0.0.0.0:3000/login
Content-Type: application/json

{
    "username": "alex",
    "password": "alex1990"
}

###
POST http://0.0.0.0:3000/logout
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImFsZXgiLCJleHAiOjE3MTI1MDgwMjh9.QeEZ-5FYv438W0xlrv9ZyiLz1QN8dZ6bGEBTnnPIAQU

{
}

### empty body
POST http://0.0.0.0:3000/signup
Content-Type: application/json

{
}

### corrupted body 1
POST http://0.0.0.0:3000/signup
Content-Type: application/json

qwerty

### corrupted body 2
POST http://0.0.0.0:3000/signup
Content-Type: application/json

{abc}

### no password
POST http://0.0.0.0:3000/signup
Content-Type: application/json

{
    "username": "alex_no_password"
}

### no username
POST http://0.0.0.0:3000/signup
Content-Type: application/json

{
    "password": "no_username"
}

### excess field
POST http://0.0.0.0:3000/signup
Content-Type: application/json

{
    "username": "alex",
    "password": "alex1990",
    "excess_field": "123"
}
