services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: tracks_service
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./migrations/0001_create_table.sql:/docker-entrypoint-initdb.d/migrations/0001_create_table.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build: .
    ports:
      - "3002:3002"
    environment:
      DATABASE_URL: postgresql://postgres:qwerty@localhost:5432/tracks_service
    depends_on:
      - database:

volumes:
  pgdata:
