name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check_building:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: CheckBuilding
        run: cargo check --verbose

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: cargo test --verbose

  check_style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: CheckFormat
        run: rustfmt --check src/* --edition 2021 --verbose
